# Site settings
name: Julian Florez
email: "jflorez@umich.edu"
url: url
description: "A blog and information about me"
author: "author"
title: "Julian Florez"
permalink: pretty
baseurl: /personalWebsite

# social
github:
  username: "julflore000"